# Language setting
language: node_js

# Version number
node_js:
  - 0.12
  #- 0.11
env:
  - var=test2
build:
  pre_ci_boot:
    image_name: drydock/u14nodall
    image_tag: master
    pull: true
    options: '--privileged=true --net=bridge -e FOO=true -e BOO=false'

 
  ci:
    - node --version
    - echo $JOB_TRIGGERED_BY_NAME
    - echo $JOB_TRIGGERED_BY_ID
   
  # - jfrog rt dl test-jfrog-ship/sample_file.tgz
    
#integrations:
 # hub:
  #  - integrationName: test-jfrogartifactory
   #   type: artifactory    
      
resources:
  - name: gitRepo-resource
    type: gitRepo
    integration: github
    pointer:
      sourceName: shiptestlink/sample-script-3
      branch: master
  - name: img-resource
    type: image
    integration: ship-docker
    pointer:
      sourceName: "shippabledocker/pipelinev2"
    seed:
      versionName: "deploy.2"
jobs:
  - name: langtest_u14javall_runCI      # required
    type: runCI             # required
    steps:                  # required
     - IN: gitRepo-resource
     - IN: img-resource
     




